AWSTemplateFormatVersion: 2010-09-09
Description: Additional stack for dotcom-components

Parameters:
  Stage:
    Type: String
  Role:
    Type: String
    Description: ARN of the role

Resources:
  S3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Sub arn:aws:s3:::support-admin-console/${Stage}/banner-deploy/*
              - !Sub arn:aws:s3:::gu-contributions-public/epic/${Stage}/*
              - !Sub arn:aws:s3:::gu-contributions-public/banner/${Stage}/*
      Roles:
        - !Ref Role

